export type SeedTopic = {
  title: string;
  research_context: string;
};

export const SEEDS: [string, string, SeedTopic[]][] = [
  // ─── SaaS & AI Tools (canvas_center) ────────────────────────────────────
  [
    'SaaS & AI Tools',
    'canvas_center',
    [
      {
        title: 'How Airbnb sold cereal boxes to survive their first year',
        research_context: 'In 2008, Brian Chesky and Joe Gebbia were $30,000 in credit card debt. They had launched Airbnb during the Democratic National Convention — renting air mattresses in their living room — but after the event, bookings dried up. To stay alive, they bought bulk cereal boxes, redesigned them as Obama O\'s and Cap\'n McCain\'s, and sold them for $40 each at the 2008 DNC. They made $30,000 and flew to SXSW to meet their first real users. Paul Graham later said "the founders were so desperate they would not die."'
      },
      {
        title: 'Patrick Collison coded Stripe from his bedroom at 19 — and nearly broke the internet',
        research_context: 'Patrick Collison was 19 when he started coding Stripe in his bedroom in Cambridge, Massachusetts. His brother John joined him after dropping out of MIT. The problem they solved was deeply personal: Patrick had tried to integrate payments for his previous startup and found it nearly impossible. Stripe\'s early pitch was dismissed by investors who said "nobody will type their credit card into a web browser." The critical moment: Elon Musk\'s X.com (later PayPal) had proven online payments worked, but Stripe\'s innovation was making it a simple API call — 7 lines of code vs 200+ pages of paperwork. Peter Thiel invested $2M after a single meeting. By 2010, Stripe was processing millions. The "near disaster": a single bug in 2011 almost double-charged every customer — caught by Patrick at 3 AM during a code review.'
      },
      {
        title: 'Jensen Huang bet Nvidia on gaming when the whole industry said 3D was a fad',
        research_context: 'In 1993, Jensen Huang co-founded Nvidia at a Denny\'s diner. The bet: 3D graphics would transform computing. Every major tech company at the time — Intel, Microsoft, IBM — believed 3D was a niche for arcade games and military simulators. Nvidia\'s first chip, the NV1, failed catastrophically. They burned through their entire $20M funding and had to lay off half the company. With weeks of runway left, Jensen bet everything on a single chip — the Riva 128 — and shipped it in 1997. It sold 1 million units in 4 months. The company went public in 1999. The lesson Jensen drilled into the culture: "Our company is 30 days from going out of business." That paranoia drove them to keep innovating through every boom and bust, eventually dominating AI hardware 25 years later.'
      },
      {
        title: 'Melanie Perkins was rejected 100 times before Canva became a $40B company',
        research_context: 'Melanie Perkins was 19, teaching university students how to use Photoshop, when she realized how absurdly hard design software was. Her idea: make design as easy as typing. She spent 2 years pitching the concept of Canva and was rejected by over 100 venture capitalists. One investor told her "I would never invest in a publishing tool" — a week later, he invested in a similar idea. The breakthrough came when she met Lars Rasmussen, a Google Maps co-founder, who introduced her to his network. She and her co-founder Cliff Obrecht lived on $15/day for years, coding the prototype on a couch in her mom\'s living room. When they finally raised funding, the entire team took a pay cut to extend runway during the 2020 downturn. By 2024, Canva was valued at $40B with 1,500 employees — and zero salespeople.'
      },
      {
        title: 'Jan Koum built WhatsApp from a gym membership fee while on food stamps',
        research_context: 'Jan Koum immigrated from Ukraine at 16, living in a government-subsidized housing project. His mother worked as a babysitter; his father wasn\'t allowed to leave Ukraine. Koum taught himself computer networking from used books he bought at a flea market. In 2009, he bought an iPhone and realized the App Store was about to explode. He built WhatsApp as a simple status-sharing app, but nobody used it. The pivot: Apple introduced push notifications, and Koum realized he could turn WhatsApp into a messaging app that showed "online" status. He ran the app on a single server for its first 2 years, funded by his savings from working at Yahoo. When money ran out, he lived on a $400/month gym membership fee — not for fitness, but because the gym let him shower there. Facebook acquired WhatsApp for $19B in 2014. Koum had 35 employees.'
      },
      {
        title: 'Luis von Ahn turned CAPTCHAs into a $700M company by tricking millions to work for free',
        research_context: 'Luis von Ahn, a Guatemalan computer science professor at Carnegie Mellon, invented CAPTCHA — those distorted letters websites use to prove you\'re human. He realized humanity was collectively wasting 500,000 hours per day typing CAPTCHAs. His insight: use that wasted time productively. He created reCAPTCHA, which used the typed words to digitize books that optical scanners couldn\'t read. Every CAPTCHA typed was actually helping digitize the New York Times archive and Google Books. Google acquired reCAPTCHA in 2009 for an estimated $700M. Von Ahn later built Duolingo, the most popular language-learning app in the world, using the same principle: people learn languages for free while translating the web. Duolingo went public in 2021 at a $6.5B valuation.'
      },
      {
        title: 'Kevin Systrom built a location check-in app first — then pivoted to what killed Kodak',
        research_context: 'Kevin Systrom studied photography in Florence but dropped out of Stanford\'s photography program to study computer science. His first app, Burbn, was a location check-in app similar to Foursquare. It was cluttered, confusing, and nobody used it. The one thing users loved: sharing photos from their check-ins. Systrom and co-founder Mike Krieger stripped Burbn down to one feature — photo sharing — and rebuilt it as Instagram in 8 weeks. They launched in October 2010. In the first 24 hours, 25,000 people signed up. The server crashed under the load; they fixed it at 3 AM. In 3 months, they had 1 million users. Mark Zuckerberg tried to buy them for $500M in 2012 — Instragram had 13 employees. The deal closed for $1B. The punchline: Instagram\'s photo filters mimicked the look of Kodak cameras. Kodak filed for bankruptcy the same year Instagram sold to Facebook.'
      },
      {
        title: 'Larry Page and Sergey Brin almost sold Google for $750,000 — and the buyer said no',
        research_context: 'In 1998, Larry Page and Sergey Brin were PhD students at Stanford who built a search engine called "BackRub." They tried to sell it to Excite (the dominant search engine at the time) for $750,000. Excite\'s CEO said no — twice. The reason: Excite believed users wanted web portals with news and weather, not a blank page with a search box. Andy Bechtolsheim, co-founder of Sun Microsystems, wrote them a $100,000 check made out to "Google Inc." — a company that didn\'t legally exist yet. The name "Google" was a misspelling of "googol" (the number 1 followed by 100 zeros). The first server was built from Lego bricks because they couldn\'t afford a proper case. Google went public in 2004 at a $23B valuation. By 2024, it was worth over $2 trillion. The Excite CEO who passed on buying it for $750K? He later said it was "the worst business decision in history."'
      },
      {
        title: 'Ivan Zhao coded Notion alone for 3 years in a tiny room before anyone cared',
        research_context: 'Ivan Zhao studied cognitive science and wanted to build the ultimate tool for thought. He started coding Notion in a tiny rented room in San Francisco, living on ramen and personal savings. For 3 years, he was the only engineer. The first version launched in 2016 to crickets — 200 users signed up, and most left within a week. Investors laughed at the idea of a "modular document editor." Zhao kept coding, sleeping under his desk, convinced that knowledge workers needed a tool that could be everything: notes, databases, wikis, project management. The turning point: a single viral tweet in 2018 showing what Notion could do. The tweet got 10,000 retweets and crashed Notion\'s server. By 2022, Notion was valued at $10B with 30 million users. Zhao still codes. His philosophy: "The best products feel like they were made by one person who really cares."'
      },
      {
        title: 'Drew Houston forgot his USB drive — and built a $10B company from that mistake',
        research_context: 'In 2007, Drew Houston was on a bus from Boston to New York when he realized he forgot his USB drive at home. He had no way to access his files. He started coding the first version of Dropbox on the bus — just a simple script that synced files across his machines. He showed it to Y Combinator, but Paul Graham was skeptical: "File sync is a feature, not a product." Dropbox launched at TechCrunch50 in 2008. The demo crashed the entire venue\'s WiFi because too many people tried to download it at once. The early growth hack: Wired\'s Chris Anderson mentioned Dropbox in a tweet — 10,000 signups in 24 hours. Dropbox now had the problem of "viral video" growth but no monetization. The survival moment: in 2011, Amazon Web Services had a massive outage that took down Dropbox for 3 days. Customers screamed. Houston realized they had to build their own infrastructure. Dropbox went public in 2018 at a $10B valuation — all because a man forgot his USB drive.'
      },
      {
        title: 'Daniel Ek built Spotify from a pirate radio bedroom in Sweden',
        research_context: 'Daniel Ek grew up in a Stockholm suburb, obsessed with music and computers. He built his first website at 13, charging $100 per site. By 18, he was a millionaire. But the music industry was dying — piracy had destroyed the album model. Ek\'s insight: piracy was a user experience problem, not a moral one. People would pay if the experience was better than stealing. He spent 2 years negotiating with record labels who saw him as the enemy. The labels demanded $1 per play — Ek offered fractions of a cent. He had to personally guarantee millions of dollars against his own savings. Spotify launched in 2008 in Europe, then the US in 2011. By 2012, it had 20 million users. The most critical deal: Steve Jobs initially blocked the Spotify iPhone app. Ek flew to Cupertino and negotiated directly. Today, Spotify has 500 million+ users and is the dominant music platform.'
      },
      {
        title: 'Nikolay Storonsky built Revolut after being rejected by 100 banks',
        research_context: 'Nikolay Storonsky was a trader at Lehman Brothers during the 2008 collapse. He watched the entire financial system melt and realized: banks were making billions while giving customers terrible service. In 2015, he left his job and built Revolut — a banking app with no branches and zero fees. He was rejected by 100+ banks and investors who said "you can\'t disrupt banking from a laptop in a coffee shop." To survive, he spent his personal savings and maxed out credit cards. The breakthrough moment: Revolut launched its travel card with real-time exchange rates and zero markup. The feature went viral among young travelers. In 2018, a single security incident (a database breach exposed 50,000 customer records) nearly killed the company. Storonsky fired the CTO that night and personally called affected customers. By 2024, Revolut was valued at $33B, with 35 million users across 50 countries.'
      },
      {
        title: 'Sebastian Siemiatkowski pitched Klarna for 3 years before anyone invested',
        research_context: 'Sebastian Siemiatkowski was 22 when he entered a business competition with the idea for Klarna — a payment method that let people buy now and pay later. He didn\'t win. Over the next 3 years, he pitched to 80 venture capital firms. All said no. One investor told him: "Swedes don\'t use credit. This will never work in Europe." He ran the company from a tiny Stockholm apartment, personally handling customer support calls at 2 AM. The company survived by processing payments for adult websites — the only merchants who would take a chance on them. In 2007, Sequoia Capital finally invested $3M. The key insight: Klarna\'s fraud rate was 1/10th the industry average because they used AI to analyze purchase patterns before anyone else in Europe. Klarna now has 150 million users and was valued at $6.7B in 2024. Siemiatkowski still answers customer emails himself.'
      },
      {
        title: 'Taavet and Kristo built Wise because a $3,000 wire transfer lost them $600 in fees',
        research_context: 'Taavet Hinrikus was an Estonian living in London who kept getting paid in euros but needed pounds. Kristo Käärmann was also Estonian in London, paid in pounds but needed euros. They realized banks were charging 5-8% on currency exchange through hidden fees and terrible exchange rates. Their solution: match each other\'s transfers directly — Taavet sent Kristo euros, Kristo sent Taavet pounds. No bank fees. In 2011, they launched Wise (originally TransferWise) to let anyone do this. The banks fought back: they blocked Wise from using banking infrastructure, lobbied regulators, and tried to kill the company. The Wise team had to route transfers through 3 different countries to bypass banking blockades. By 2023, Wise was moving $12B per month across borders, saving customers $3M per day in hidden fees. Taavet and Kristo solved a $200B problem that banks had no incentive to fix.'
      },
      {
        title: 'Markus Villig dropped out of high school at 19 to fight Uber — and built Europe\'s last ride-hail survivor',
        research_context: 'Markus Villig was 19, still in high school in Estonia, when he realized Uber was coming to Europe. His parents wanted him to finish school. He dropped out anyway. With no coding experience and no money, he built the first version of Bolt (then Taxify) by learning to code in 2 months from YouTube tutorials. He cold-emailed 50 investors and got 50 rejections. Finally, a single Estonian angel investor agreed to meet — Markus pitched him in a McDonald\'s. He got $5,000. For 2 years, Bolt existed on $5,000. Markus personally recruited drivers by standing at bus stops in Tallinn. The survival moment: in 2016, Uber launched in Estonia and tried to crush Bolt by subsidizing rides at 70% below cost. Markus couldn\'t match the spending. His countermove: focus on smaller European cities Uber ignored, building driver loyalty with lower commissions. Uber eventually pulled out of Eastern Europe. By 2024, Bolt operated in 45 countries with 100 million+ users.'
      },
      {
        title: 'Ilkka Paananen almost quit gaming — then Supercell made $5B from 4 games',
        research_context: 'Ilkka Paananen was CEO of a mobile gaming company that failed and was sold for scraps. He nearly quit the industry. Instead, he started Supercell in 2010 in Helsinki with $10M in a market everyone said was dead — mobile games. The philosophy: kill projects fast. Supercell canceled 14 games for every one they launched. The first hit, Clash of Clans, launched in 2012 and made $1M per day within 6 months. The second hit, Hay Day, followed. By 2013, Supercell was making $2.4M per day from just 2 games. The most painful cancellation: a game internally called "Battle Buddies" tested amazingly but Paananen killed it because it wasn\'t "iconic enough." In 2016, Tencent bought 84% of Supercell for $8.6B. The company had just 4 games and 180 employees. Paananen\'s rule: "Small teams, big bets, and the courage to kill your darlings."'
      },
      {
        title: 'Eric Yuan left Cisco 11 times to build Zoom — then the pandemic made him a billionaire',
        research_context: 'Eric Yuan moved from China to the US in 1997, sleeping on a friend\'s couch. He joined WebEx, a video conferencing company, and became its VP of Engineering. Cisco acquired WebEx for $3.2B in 2007. Yuan pitched Cisco leadership on mobile video conferencing — they said no, 11 times. Finally, he quit and started Zoom in 2011, taking 40 engineers with him. The insight: video conferencing was terrible because it tried to route everything through centralized servers. Zoom used a hybrid architecture — first 10 minutes free on Zoom\'s servers, then routed through the most efficient path. By 2019, Zoom had 10 million daily users. Then COVID-19 hit. In March 2020, Zoom went from 10 million to 200 million daily users in 3 weeks. Yuan personally approved the purchase of 10,000 new servers in 48 hours. The security nightmare: "Zoombombing" made headlines. Yuan paused all feature development for 90 days to fix security. By 2023, Zoom was a $20B company.'
      },
      {
        title: 'Dylan Field built Figma in a browser when everyone said native apps were the only way',
        research_context: 'Dylan Field studied computer science at Brown and interned at Flipboard and LinkedIn. In 2012, he had an idea that sounded insane: build a professional design tool that runs entirely in a web browser. Every competitor — Sketch, Adobe, InVision — was built as a native app because browsers couldn\'t handle the processing power required for vector graphics. Field joined Y Combinator and spent 3 years building Figma before launching a beta. The breakthrough: WebGL and WebAssembly had matured enough to make browser-based vector editing possible. Designers were skeptical. The turning point: Figma made collaboration the core feature — multiple people could edit the same file simultaneously, something no native app could do. Adobe offered $20B for Figma in 2022 (blocked by regulators). By 2024, Figma had 4 million users and had killed Sketch, InVision, and Framer as competitors — all because a college kid believed the browser was ready.'
      },
      {
        title: 'Tom Preston-Werner built GitHub while traveling the world with no office',
        research_context: 'Tom Preston-Werner was a developer who hated how hard it was to share code. In 2007, he built the first version of GitHub while traveling through Southeast Asia — coding from internet cafes in Thailand and the Philippines. He had no office, no employees, and no business plan. The core insight: Git (a version control system) was brilliant but had a terrible user interface. GitHub made it visual and social. The first 100 users were friends he personally emailed. By 2009, GitHub had 50,000 users — without spending a dollar on marketing. The crisis moment: in 2009, GitHub\'s database got corrupted. Preston-Werner spent 48 hours recovering it from backups, losing only 1 hour of data. He posted a public postmortem that became legendary in developer culture for its transparency. Microsoft acquired GitHub for $7.5B in 2018. The company had 0 salespeople, 0 offices, and 200 employees — all remote, a decade before remote work was normal.'
      },
      {
        title: 'Niklas Zennström built Skype by accident — and sold it to eBay for $4.1B',
        research_context: 'Niklas Zennström and Janus Friis were the founders of Kazaa, the file-sharing network that nearly got them sued out of existence by the music industry. As the lawsuits mounted, they realized the same peer-to-peer technology that shared music files could route phone calls — for free. Skype launched in 2003 with no marketing budget. The first million users came from word-of-mouth in 3 weeks. The problem: Skype had no revenue. Zennström famously said "we\'ll figure out the business model later." eBay acquired Skype for $4.1B in 2005 — and then spent 5 years trying and failing to integrate it before writing off most of the value. Zennström and Friis had already left, taking the core P2P technology with them. They licensed it back to eBay at $50M/year. In 2011, Microsoft bought Skype for $8.5B. Zennström built a billion-dollar company twice from the same technology — essentially by accident.'
      },
    ]
  ],

  // ─── Financial Forensics (canvas_area) ──────────────────────────────────
  [
    'Financial Forensics',
    'canvas_area',
    [
      {
        title: 'The $4.7M typo that erased a lifetime fortune in 14 seconds',
        research_context: 'In 2012, a trader at Knight Capital Group accidentally left a single line of old code running during an upgrade. The code was supposed to be deleted — it was a dormant testing script. Over 45 minutes on August 1, 2012, that code executed 4 million stock trades, buying high and selling low in an infinite loop. The company lost $440 per second. By the time someone hit the kill switch, Knight Capital had lost $460M — more than the company was worth. They had 3 days to find a buyer before going bankrupt. The CEO personally called every rival firm begging for a bailout. A consortium paid $400M for the company\'s assets. A single unused line of code, left running for 14 seconds too long, destroyed a 17-year-old company that once handled 17% of all US stock trades.'
      },
      {
        title: 'How Wirecard fooled auditors into believing $2.1B existed in a country with no banks',
        research_context: 'Wirecard was a German payments company worth $28B at its peak — the darling of German fintech. In 2019, a Financial Times journalist noticed something strange: Wirecard claimed $2.1B in cash was held in trust accounts in Singapore and the Philippines. The problem: the Philippines has a law that prohibits foreign companies from holding trust accounts. The FT\'s investigation took 4 years of digging through shell companies in Dubai, Singapore, and the Philippines. Wirecard\'s COO Jan Marsalek was exposed as a spymaster who had faked contracts, created phantom business partners, and bribed a Filipino bank executive to forge documents. The "trust accounts" didn\'t exist. The $2.1B was imaginary. Wirecard filed for insolvency in June 2020. Marsalek fled to Russia and is still a fugitive. The CEO was sentenced to 12 years in prison. Deloitte, the auditor, paid $200M to settle negligence claims.'
      },
      {
        title: 'Bernie Madoff ran a $64B Ponzi scheme without making a single trade',
        research_context: 'Bernie Madoff ran the largest Ponzi scheme in history — $64B in fictional wealth. The mechanics were stunningly simple: he never made a single trade. When a client wanted to invest, the money went into a Chase bank account. When a client wanted to withdraw, the money came out of the same account. Madoff fabricated trade confirmations, account statements, and tax documents showing returns of 10-12% every year, through bull and bear markets. The only reason he was caught: the 2008 financial crisis caused a wave of redemption requests he couldn\'t fake. A single analyst, Harry Markopolos, had been trying to expose Madoff since 1999. He submitted 5 detailed reports to the SEC over 9 years — all ignored. Madoff was arrested on December 11, 2008, confessed to his sons the same day. They turned him in. He died in prison in 2021. His victims: 40,000 people across 136 countries, including Holocaust survivors who lost their entire life savings.'
      },
      {
        title: 'A 28-year-old bankrupted the Queen of England\'s bank with one trade',
        research_context: 'Nick Leeson was 28 years old, a trader at Barings Bank — the oldest merchant bank in England, founded in 1762. The Queen herself banked there. Leeson was sent to Barings\' Singapore office to "arbitrage" — profit from tiny price differences in Nikkei futures across different exchanges. Instead, he started making unauthorized speculative trades. When he lost money, he hid the losses in a secret error account #88888. For 3 years, he doubled down on increasingly desperate bets to recover his losses. By the end, his trading position was larger than Barings\' entire market cap. On February 23, 1995, Leeson lost $1.4B — bankrupting a bank that had survived the Napoleonic Wars, both World Wars, and the Great Depression. He fled to Malaysia, was caught, and served 6.5 years in a Singapore prison. The Queen lost her banking relationship. Barings was sold to Dutch bank ING for £1.'
      },
      {
        title: 'Theranos faked a revolution using standard Siemens machines and a lot of confidence',
        research_context: 'Elizabeth Holmes dropped out of Stanford at 19 with a vision: a machine that could run 200 medical tests from a single drop of blood. The technology didn\'t exist. For 15 years, she faked it. The secret: when demonstrating "the Edison" to investors and regulators, Theranos used standard Siemens blood analyzers hidden behind drywall. Patients who visited Theranos\'s Walgreens locations had their blood drawn normally — then secretly tested on Siemens equipment. When Walgreens executives visited the lab, Holmes had employees open empty drawers labelled "Quality Control" while real tests ran on hidden machines. The deception unraveled when The Wall Street Journal\'s John Carreyrou investigated in 2015 — employees told him about the hidden Siemens machines, the barcodes swapped to hide the truth, and the falsified test results that gave patients incorrectly diagnosed medical conditions. Holmes was convicted of fraud in 2022 and sentenced to 11 years. Her investors lost $1B.'
      },
      {
        title: 'FTX backed billions in loans with a token Alameda invented out of thin air',
        research_context: 'Sam Bankman-Fried\'s FTX was the second-largest crypto exchange in the world, valued at $32B. The problem: FTX\'s sister trading firm, Alameda Research, had taken billions of dollars in customer deposits from FTX and used them as collateral for loans. The "collateral" was a token called FTT — a token that Alameda itself had created and controlled the price of. When CoinDesk revealed this arrangement in November 2022, FTT crashed from $22 to $2 in 48 hours. Alameda\'s $10B in loans were immediately under-collateralized. FTX halted withdrawals. $8B in customer deposits had vanished. The CEO and celebrity endorsers (Tom Brady, Steph Curry, Larry David) were sued. Bankman-Fried was convicted of 7 counts of fraud in 2023 and sentenced to 25 years. The auditing firm that signed off on FTX\'s financials? A company called Armanino that had 25 employees and no crypto experience.'
      },
      {
        title: 'Lehman Brothers hid $50B in debt using a trick called Repo 105',
        research_context: 'In 2008, Lehman Brothers collapsed with $639B in assets — the largest bankruptcy in US history. The mechanism was a clever accounting trick: Repo 105. Lehman would "sell" $50B of its worst assets to European banks at the end of each quarter, with an agreement to buy them back a few days later. Under accounting rules, this counted as a "sale" that temporarily removed $50B of debt from the balance sheet. Lehman\'s reported leverage ratio went from 30:1 to a healthier 20:1 — just long enough for the quarterly report to be filed. Then they bought the assets back. The SEC approved this practice. The CFO testified that Repo 105 was "standard in the industry." The bankruptcy examiner\'s report: $50B was hidden from investors, regulators, and the board. The CEO Dick Fuld testified to Congress that he "didn\'t know" about Repo 105 until the collapse. Lehman\'s stock went from $67 to $0. The global financial crisis followed.'
      },
      {
        title: 'The Indonesian gold mine that held absolutely no gold',
        research_context: 'In 1993, a Canadian mining company called Bre-X announced they had discovered the largest gold deposit in history at Busang, deep in the Indonesian jungle. The stock went from $0.30 to $286 per share — a market cap of $4.4B. The CEO, David Walsh, became a billionaire. The problem: the core samples were "salted" — crushed gold was mixed into worthless rock by the site geologist, Michael de Guzman. When the company\'s own due diligence team flew to Indonesia to verify, de Guzman either fell or jumped from a helicopter over the jungle. His body was never found. When independent tests were finally done, the site contained zero commercial gold. The entire company was worth $0. The stock crashed from $286 to $0 in a single day. Walsh lost everything and died broke in 1998. The gold never existed. Busang was a worthless patch of mud.'
      },
      {
        title: 'Enron booked billions in revenue on deals that entirely failed',
        research_context: 'Enron was the 7th largest company in America in 2000 — $100B market cap, named "America\'s Most Innovative Company" by Fortune 6 years running. The entire company was a mirage. Enron\'s "innovative" accounting: they used mark-to-market accounting, which let them book the entire projected profit of a 20-year deal in year one — even if the deal later failed. They created hundreds of off-balance-sheet partnerships (LJM, Raptor) that existed solely to buy Enron\'s bad assets at artificially high prices. The CFO, Andrew Fastow, ran these partnerships and personally made $30M. When the scheme collapsed in 2001, Enron restated 5 years of earnings — $591M in profits became $1.2B in losses. The stock went from $90 to $0.26. 20,000 employees lost their jobs and pensions. Arthur Andersen, the auditing firm, was convicted of obstruction of justice and went out of business. The scandal directly led to the Sarbanes-Oxley Act.'
      },
      {
        title: 'The Hunt Brothers tried to corner the global silver market — and lost everything',
        research_context: 'In 1979, billionaire brothers Nelson Bunker Hunt and William Herbert Hunt decided to corner the global silver market. They bought 200 million ounces of silver — more than the entire global supply — using heavily leveraged futures contracts. Silver went from $6 to $50 an ounce in 9 months. The Hunt brothers were sitting on $10B in paper profits. The problem: the exchanges changed the rules. The Commodity Futures Trading Commission and Comex changed margin requirements, making it impossible for the Hunts to hold their positions. Silver crashed from $50 to $11 in 3 days. The Hunt brothers couldn\'t meet their margin calls — they owed $1.7B. They defaulted. The US government had to step in with $1.1B in emergency loans to prevent a banking crisis. The Hunts lost their entire fortune, including their oil company, real estate, and a famous collection of Arabian horses. At his peak, Bunker Hunt was worth $16B. He died with $10M.'
      },
      {
        title: 'Nobel laureates blew up a $126B hedge fund and nearly took down Wall Street',
        research_context: 'Long-Term Capital Management (LTCM) was founded in 1994 by John Meriwether, the former Salomon Brothers bond trader. The partners included Myron Scholes and Robert C. Merton — both Nobel Prize-winning economists whose options pricing model was taught in every finance class. The thesis: using complex math to exploit tiny pricing anomalies in bond markets. LTCM generated 40% annual returns for 3 years, with zero losing months. At its peak, it had $126B in assets and $1.4T in derivatives exposure. The problem: the models assumed markets would stay "rational." In 1998, Russia defaulted on its debt — a scenario the Nobel models said could "never happen." Correlated losses hit every position simultaneously. LTCM lost $4.6B in 4 months. The Federal Reserve organized a $3.6B bailout from 14 banks to prevent a systemic collapse. One partner\'s reaction: "We were using models that won the Nobel Prize. We forgot that models describe the world, not prescribe it."'
      },
      {
        title: 'The Great Salad Oil Swindle that crashed Wall Street',
        research_context: 'In 1963, Anthony "Tino" De Angelis and his company, Allied Crude Vegetable Oil Refining, took out billions of dollars in loans using soybean oil as collateral. The problem: there was no soybean oil. De Angelis had filled his storage tanks with seawater, with a thin layer of oil floating on top. Inspectors would climb the tanks, stick a measuring rod in, and hit oil — never realizing the bottom 95% was salt water. He also used secret pipes to pump oil between tanks, making the same oil appear in multiple locations. When the scheme finally collapsed, De Angelis had defrauded 51 banks of $175M ($1.6B in today\'s dollars). The collapse triggered a chain reaction: American Express (who had lent $144M against phantom oil) nearly went bankrupt. The stock market crashed 6% in a single day. De Angelis went to prison for 7 years. When one victim asked him why, he said: "Because I wanted to be the richest man in the world."'
      },
      {
        title: 'The 36-year-old who spoofed the market from his bedroom and shook the global economy',
        research_context: 'Navinder Singh Sarao was a 36-year-old British day trader who lived with his parents in suburban London. From his bedroom, using a standard desktop computer, he placed fake sell orders for S&P 500 futures worth billions of dollars — a practice called "spoofing." He would place massive orders he had no intention of executing, creating the illusion of supply, driving the price down, then cancel the orders and buy at the lower price. His trading pattern was so aggressive that multiple government investigations concluded he contributed to the 2010 "Flash Crash" — a 36-minute event where the Dow Jones dropped 1,000 points (nearly $1 trillion in market value) before recovering. The US Department of Justice extradited him from the UK in 2016. His defense: "I was just trading a strategy. Everyone does it." He was sentenced to 1 year of home confinement. The market he manipulated from his bedroom was worth $4 trillion.'
      },
      {
        title: 'The crypto CEO who faked his death with $250 million of customer money',
        research_context: 'In 2018, Gerald Cotten, CEO of Canadian crypto exchange QuadrigaCX, died suddenly while traveling in India from complications of Crohn\'s disease. His death was a catastrophe: Cotten was the only person who knew the password to the cold wallets holding $250M in customer cryptocurrency. Except: investigators soon discovered that "cold wallets" didn\'t exist. Cotten had been running a sham exchange where customer deposits were used to pay other customers\' withdrawals (a Ponzi scheme). The wallets contained $0. The $250M was gone — spent on luxury homes, yachts, and personal expenses. Cotten\'s death was perfectly timed to conceal the fraud. Some believe he faked his death — his LinkedIn profile shows him accepting a "congratulations on your new position" message 2 months after his reported death. The Canadian government investigated. His wife, Jennifer Robertson, surrendered assets to a trustee. To date, $0 of the $250M has been returned to customers.'
      },
      {
        title: 'The chatroom cartel that rigged global interest rates and faced $9B in fines',
        research_context: 'Between 2005 and 2010, a group of traders at the world\'s largest banks — Barclays, UBS, Deutsche Bank, Citigroup, JP Morgan — communicated in online chatrooms with names like "The Cartel" and "The Bandits\' Club." They colluded to manipulate the Libor interest rate, which determines the interest on $350 trillion in financial products worldwide: mortgages, student loans, credit cards, derivatives. The manipulation was casual: a trader would message "I need 3-month Libor at 0.37 today pls" and another would respond "done." The rate was set by a daily poll of banks asking "at what rate could you borrow?" — and the answers were whatever the chatroom agreed on. The scheme ran for 5 years before regulators caught on. The total fines: Barclays paid $450M, UBS $1.5B, Deutsche Bank $2.5B, RBS $612M, and multiple others. Total: over $9B in penalties. Three traders were convicted. The rest kept their bonuses.'
      },
      {
        title: '1MDB: The $4.5B heist that funded the Wolf of Wall Street and brought down a prime minister',
        research_context: '1MDB was a Malaysian sovereign wealth fund created in 2009. By 2015, $4.5B had been stolen from it in what the US Department of Justice called "the largest kleptocracy case in American history." The mastermind: Jho Low, a Malaysian financier who orchestrated the theft through a web of shell companies in Singapore, Switzerland, and the Cayman Islands. The stolen money funded: a $250M superyacht, a $100M penthouse in New York, the production of "The Wolf of Wall Street" (Red Granite Pictures, owned by a Malaysian official\'s stepson), a $50M pink diamond for an Hollywood actress, real estate in London and Beverly Hills, and bribes for government officials across Malaysia. The loans were laundered through Goldman Sachs, who earned $600M in fees. Goldman paid $3.9B in penalties. Jho Low remains a fugitive. The Malaysian Prime Minister Najib Razak was convicted and sentenced to 12 years in prison. $4.5B stolen from a country whose median income is $10,000/year.'
      },
      {
        title: 'The man who sold the Eiffel Tower — twice',
        research_context: 'Count Victor Lustig was one of history\'s most audacious con artists. In 1925, he learned that the Eiffel Tower was in disrepair and that Paris considered demolishing it. Lustig invited 6 scrap metal dealers to a secret government meeting at a hotel, posing as a government official. He explained the tower was being sold for scrap — confidentially, to avoid public outrage. He selected the highest bidder, André Poisson, who paid 100,000 francs (about $500,000 today). Lustig collected the money and fled to Vienna. When Poisson realized he was scammed, he was too embarrassed to report it. So Lustig returned to Paris one month later and did it again — selling the Eiffel Tower to a DIFFERENT scrap dealer. This second victim went to the police. Lustig fled to the US where he continued conning people, including selling counterfeit $100 bills (the "Lustig Note," one of the most convincing counterfeits ever made). He spent 20 years in Alcatraz.'
      },
      {
        title: 'The Pigeon King: How a single Ponzi schemer conned 3,000 farmers out of retirement savings',
        research_context: 'In the early 2000s, a Canadian named Michael "Pigeon King" Mazar promised farmers a fortune: breed his special racing pigeons, and he would buy every squab (baby pigeon) at $40 each — 10x the market price. Over 3,000 farmers across Canada and the US signed contracts, spending their life savings on pigeon coops and breeding pairs. The scheme: Mazar had no buyers for the pigeons. He was paying earlier farmers with money from new farmers — a classic Ponzi. The "breeding pairs" he sold were ordinary pigeons purchased at auctions for pennies. By 2009, the scheme collapsed when Mazar could no longer recruit enough new farmers. The total losses exceeded $50M. Hundreds of farmers lost their retirement savings, their farms, and their homes. One farmer shot himself. Others were left with thousands of worthless pigeons they couldn\'t feed. Mazar was convicted of fraud in 2012 and sentenced to 7 years.'
      },
      {
        title: 'The $6B natural gas weather bet that backfired',
        research_context: 'In 2006, hedge fund Amaranth Advisors had $9B in assets under management. They made a massive bet: natural gas prices would fall through the summer. The trader, Brian Hunter, had made $1B for the fund the previous year on a similar bet. In 2006, he went bigger — controlling 10% of the entire US natural gas futures market. Then Hurricane Katrina didn\'t hit the Gulf. A warm winter destroyed demand. Natural gas prices went up instead of down. Amaranth lost $6B in 3 weeks — the largest hedge fund collapse in history at the time. The board liquidated the fund at fire-sale prices. Hunter was fined $30M by the CFTC and banned from trading. The lesson: a single bet on a single commodity, even if it worked before, can destroy a company when it doesn\'t. The $6B loss happened so fast that Amaranth\'s risk models didn\'t update quickly enough to trigger a warning.'
      },
      {
        title: 'Just Mayo bought its own mayonnaise to fake demand — and got caught by a deli owner',
        research_context: 'Hampton Creek was a Silicon Valley "unicorn" startup worth $1.1B that made plant-based mayonnaise called Just Mayo. The CEO, Josh Tetrick, raised $220M from investors including Bill Gates and Peter Thiel. In 2014, a New York deli owner named Rob Anderson noticed something strange: people kept coming in, buying multiple jars of Just Mayo, and leaving without ordering food. They were buying it in bulk — paying full retail price. He tracked the credit card transactions and found they were from the same credit card. He called the SEC. The investigation revealed: Hampton Creek employees were sent to stores across the country, given company credit cards, and told to buy as much Just Mayo as possible — even instructed to "open a store credit account" to make the purchases look like wholesale orders. The goal: boost reported sales figures to impress investors before a funding round. Hampton Creek denied the allegations but settled with the SEC for $500,000.'
      },
    ]
  ],

  // ─── Stoic Philosophy (canvas_station) ───────────────────────────────────
  [
    'Stoic Philosophy',
    'canvas_station',
    [
      {
        title: 'James Stockdale survived 7 years as a POW using a single Stoic principle',
        research_context: 'Rear Admiral James Stockdale was the highest-ranking US prisoner of war in Vietnam. He was shot down in 1965 and spent 7.4 years in the Hanoi Hilton — including 4 years in solitary confinement and 20 months in leg irons. He was tortured 15 times. His survival secret: Stoicism. Stockdale had read Epictetus at Stanford\'s military academy. The principle that kept him alive: the dichotomy of control — "Some things are up to us, some are not." Stockdale could not control being shot down, captured, or tortured. He could control his response — his integrity, his resistance, his refusal to break. He created a covert tap-code communication system that became the standard across all POW camps. When released in 1973, he walked out with a limp and a Stoic calm that confused his captors. Later, he wrote: "I never lost faith in the end of the story. I knew I would prevail — but I was wrong about the length of the interval."'
      },
      {
        title: 'Viktor Frankl found meaning in a concentration camp — and invented a new therapy',
        research_context: 'Viktor Frankl was a Jewish psychiatrist arrested by the Nazis in 1942. He survived 4 concentration camps, including Auschwitz, while his parents, brother, and pregnant wife died. In the camps, he observed a psychological pattern: those who found meaning in their suffering were far more likely to survive than those who focused on avoiding pain. He called this "logotherapy" — the belief that the primary human drive is not pleasure but finding meaning. His book "Man\'s Search for Meaning" has sold 16 million copies. The core insight: "Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom." Frankl applied Stoicism to the worst circumstances imaginable and proved it works — not as philosophy, but as survival.'
      },
      {
        title: 'Marcus Aurelius wrote Meditations during a plague that killed 5 million people',
        research_context: 'Marcus Aurelius was Roman Emperor from 161 to 180 AD, widely considered the last of the "Five Good Emperors." His reign was one catastrophe after another: a devastating plague (the Antonine Plague, which killed 5M people), constant wars on the northern frontier, a rebellion in the east, a devastating flood of the Tiber, and his own failing health. During the plague — when 2,000 people were dying per day in Rome — Marcus wrote his "Meditations," a private journal of Stoic exercises never intended for publication. He wrote: "The art of living is more like wrestling than dancing." He wrote about the plague: "A plague might devour the city — but so does ambition, so does stupidity." He died at 58 of a terminal illness. His final words: "Weep not for me — think of the plague and the common fate of all." Meditations, written in blood and plague, became the foundational text of Western philosophy.'
      },
      {
        title: 'Epictetus was a crippled slave who became Rome\'s greatest mind',
        research_context: 'Epictetus was born a slave in 50 AD in Hierapolis (modern Turkey). His leg was purposely broken by his master (some sources say in a torture device). He walked with a limp for life. As a slave, he studied philosophy under Musonius Rufus — the only Roman senator to publicly oppose Nero. When Epictetus finally gained his freedom, he founded one of the most influential philosophy schools in the ancient world. His students included senators, generals, and future historians. He taught: "It\'s not what happens to you, but how you react to it that matters." The 1950 translation had a preface by a young naval officer named James Stockdale. Epictetus never wrote anything himself — his student Arrian recorded his lectures as "The Discourses" and the "Enchiridion." A crippled slave, owning nothing, became the most sought-after teacher in Rome. His words still guide modern Stoics 2,000 years later.'
      },
      {
        title: 'Seneca treated his exile to a barren island like a vacation — and it changed his life',
        research_context: 'Seneca was a Roman statesman, playwright, and one of history\'s wealthiest philosophers. In 41 AD, Emperor Claudius exiled him to Corsica — a barren, rocky island with brutal winters. Exile was considered worse than death for a Roman aristocrat. Seneca\'s response: he wrote his "Consolation to Helvia" (his mother), describing Corsica not as punishment but as opportunity. He grew a garden, studied natural phenomena, and wrote some of his best essays. He practiced what he called "premeditatio malorum" — visualizing worst-case scenarios in advance so they lose their power when they arrive. 8 years later, Claudius\'s wife Agrippina recalled Seneca to tutor her son Nero. Seneca became the most powerful man in Rome for a decade. When Nero later forced him to commit suicide, Seneca\'s friends wept. He asked them: "Where are your Stoic principles? What has become of the wisdom we studied?"'
      },
      {
        title: 'Zeno founded Stoicism after losing his entire fortune in a shipwreck',
        research_context: 'Zeno of Citium was a wealthy merchant in 300 BC. He was shipping a cargo of purple dye (worth a fortune) when his ship sank in a storm. He lost everything. Stranded in Athens, he wandered into a bookshop and picked up Xenophon\'s "Memorabilia" about Socrates. He asked the bookseller: "Where can I find a man like this?" The bookseller pointed to Crates the Cynic. Zeno studied under Crates for 10 years, then began teaching his own philosophy in the Stoa Poikile (Painted Porch) — hence "Stoicism." His message: external goods (wealth, status, health) are "indifferent" — they don\'t determine your happiness. The shipwreck that took everything was the best thing that ever happened to him, because it forced him to discover what he actually needed. Zeno\'s school lasted 500 years and influenced Christianity, the Enlightenment, and modern cognitive behavioral therapy.'
      },
      {
        title: 'Cato the Younger chose death over living under a tyrant — and his choice changed Rome forever',
        research_context: 'Cato the Younger was Marcus Porcius Cato, a Roman senator famous for his unwavering integrity. When Julius Caesar crossed the Rubicon and started a civil war, Cato joined Pompey\'s side. After Caesar\'s victory at Thapsus in 46 BC, Cato\'s army surrendered. Cato refused to ask for mercy or accept Caesar\'s rule. His friends begged him to negotiate. He calmly read Plato\'s "Phaedo" (about Socrates\'s death), then stabbed himself. His friends found him alive and called a doctor. Cato ripped open his own stitches and died holding his entrails. Caesar reportedly said, "Cato, I envy your death, for you envied my life." Cato became the ultimate symbol of Stoic resistance: a man who would rather die free than live enslaved. Augustus Caesar later praised him. His martyrdom was cited by the American founders as the model of resistance to tyranny.'
      },
      {
        title: 'Cleanthes hauled water all night so he could study philosophy by day',
        research_context: 'Cleanthes of Assos was a former boxer who walked to Athens with only 4 drachmas (about $400 in today\'s money) to study philosophy under Zeno. He couldn\'t afford tuition, so he found a job: hauling water for gardens at night. By day, he studied Stoicism. He was mocked as "the water carrier" by richer students. He never took a day off for 19 years. Zeno would test Cleanthes\'s understanding by making him recite Stoic arguments from memory — and Cleanthes would repeat them back with perfect precision, proving he didn\'t need sleep to learn. When Zeno died, Cleanthes became the second head of the Stoic school. His most famous student: Chrysippus. His philosophy: "Do your duty, whatever the cost." The lesson: if you want wisdom badly enough, you\'ll find a way — even if you have to haul water all night.'
      },
      {
        title: 'Agrippinus went to dinner when told he\'d be executed tomorrow',
        research_context: 'Paconius Agrippinus was a Roman Stoic senator under Emperor Nero. When a messenger arrived with news that the Senate had condemned him to death, Agrippinus was preparing for dinner. He asked: "Is my sentence announced?" The messenger was confused. "Yes. You are to die tomorrow." Agrippinus said: "Then let us dine." Epictetus recounts this as the ultimate example of the dichotomy of control. Agrippinus knew: his own life was not up to him once the Senate had voted. But how he spent his last evening WAS up to him. He chose dinner and conversation over panic and tears. The story is even more powerful: Agrippinus\'s father had been executed by the same regime. He knew exactly what awaited him. He went to dinner anyway. Epictetus taught this to his students: "I must die. Must I die weeping? Someone will say: I will put you in chains. What do you mean, man? You will chain my leg — not my will."'
      },
      {
        title: 'How to use Stoicism to survive a layoff without losing your identity',
        research_context: 'Getting laid off feels like a personal failure — but Stoicism offers a powerful reframe. Marcus Aurelius wrote: "You have power over your mind — not outside events. Realize this, and you will find strength." When you\'re laid off, the external event (the layoff) is not up to you. But everything else is: your response, your next move, your dignity. The Stoic exercise "premeditatio malorum" suggests you visualize a layoff before it happens — not to be pessimistic, but to remove its power when it arrives. Seneca said: "He robs present ills of their power who has perceived their coming beforehand." Practical steps from Stoicism: (1) Accept the loss — the job was an external, not your worth. (2) Focus on what you control — your resume, networking, skills. (3) Reframe — Epictetus said "Circumstances don\'t make the man, they reveal him." A layoff reveals your resilience.'
      },
      {
        title: 'The Stoic approach to rejection: How Marcus Aurelius handled betrayal by his closest ally',
        research_context: 'In 175 AD, Marcus Aurelius faced the worst betrayal of his reign: Avidius Cassius, one of his most trusted generals, declared himself emperor and seized control of the Eastern provinces. Cassius had been Marcus\'s friend for decades. Most emperors would have hunted Cassius down and executed his family. Marcus\'s response: he wrote about it in Meditations — "When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly... but I have seen the beauty of good, and the ugliness of evil." He sent a message to the Senate: "I beg and entreat you to treat Cassius\'s family with mercy — his son, his son-in-law, his associates." Before the message arrived, Cassius had already been killed by his own soldiers. Marcus wept. His advice for modern rejection and betrayal: "The best revenge is not to be like your enemy."'
      },
      {
        title: 'Musonius Rufus argued that exile was the best thing that could happen to a philosopher',
        research_context: 'Gaius Musonius Rufus was the most influential Stoic philosopher you\'ve never heard of — he taught Epictetus and was called the "Roman Socrates." He was exiled THREE times. First by Nero (to a desolate island), then by Vespasian (exempted but challenged), then again. Each time, he continued teaching from exile, attracting crowds of students who traveled to hear him. He argued that exile was optimal for a philosopher because it stripped away attachments, freed you from social obligations, and gave you time to think. "What prevents a philosopher from making progress while in exile? They take away my money, but my thoughts remain." His students founded philosophical schools across the Roman world. He taught that philosophy wasn\'t intellectual exercise — it was a way of life that applied to everyone, including women, slaves, and the poor. When told to stop teaching, he said: "I will teach as long as I live."'
      },
      {
        title: 'Marcus Aurelius sold the palace treasures and the imperial wardrobe to avoid taxing the poor',
        research_context: 'Most Roman emperors taxed the poor to fund wars and palaces. When Marcus Aurelius needed money for the war against the Germanic tribes, he did the opposite: he held a massive public auction of imperial treasures. He sold golden statues, silk robes, jeweled furniture, and even his wife\'s jewelry. He auctioned the imperial wardrobe at the Forum of Trajan. He refused to raise taxes on the provinces. When the plague depopulated Rome\'s tax base, he used his personal fortune to fund grain imports for the poor. Meditations: "A man should be upright — not kept upright." The lesson for modern life: true leadership means sacrifice. When your team has to tighten budgets, the leader should personally take the hardest cut. Marcus Aurelius, the most powerful man on earth, chose to sell his own possessions to protect the poor from taxes.'
      },
      {
        title: 'Seneca practiced poverty monthly to destroy his fear of losing wealth',
        research_context: 'Seneca was one of the richest men in Rome — possibly worth $100M in today\'s terms. He also knew that wealth could breed fear: the more you have, the more you fear losing it. His solution: practice poverty. Every month, Seneca would voluntarily live for 3-4 days on the bare minimum — bread, water, a rough blanket. He wrote: "Set aside a certain number of days, during which you shall be content with the scantiest and cheapest fare. Let your cell have nothing in it that you would not look upon if taken away." He called this "the power of the prepared mind." By experiencing poverty voluntarily, he removed its terror. When Nero eventually forced him to commit suicide, Seneca had no fear of losing anything — he had practiced losing everything his whole life. Modern Stoics call this "voluntary discomfort" and practice it with cold showers, fasting, or sleeping on the floor.'
      },
      {
        title: 'How Epictetus taught a student to deal with toxic people — in one brutal paragraph',
        research_context: 'One of Epictetus\'s students complained about a particularly difficult person — someone who was rude, arrogant, and impossible to work with. Epictetus\'s response was only one paragraph, but it\'s the most practical advice on toxic people ever written: "If someone is ignorant of something, they are not harmed by the ignorance — they ARE the ignorant one. If you are harmed by their behavior, the fault is not in them but in your judgment of their behavior. When someone acts badly, remind yourself that they acted according to their own rational principles — wrong though those principles may be. Their behavior says nothing about you. It says everything about them." He concluded: "Does a horse get angry when another horse misbehaves? No — it simply ignores it. The wise man is not angry with the wicked — he is perplexed by them." The student had no retort. Epictetus had shut the argument with pure logic: someone else\'s bad behavior is their problem, not yours.'
      },
      {
        title: 'The Stockdale Paradox: Why the Stoic optimists died first in Vietnam POW camps',
        research_context: 'James Stockdale noticed a pattern among his fellow POWs in Vietnam. The optimists — the men who said "we\'ll be home by Christmas" — died first. When Christmas came and went, they broke. The men who survived were the ones who accepted the brutal reality (they could be there for 7+ years) while maintaining absolute faith that they would eventually prevail. He called this the "Stockdale Paradox": you must retain faith that you will prevail in the end, regardless of the difficulties, AND at the same time confront the most brutal facts of your current reality, whatever they might be. This was pure Stoicism: control what you can (your effort, your integrity, your tap-code system), accept what you can\'t (your release date), and never confuse the two. Jim Collins popularized the Stockdale Paradox in "Good to Great" as the key trait of companies that outperformed the market by 10x.'
      },
      {
        title: 'Diogenes the Cynic mocked Alexander the Great to his face and lived',
        research_context: 'Diogenes of Sinope was a famous Cynic philosopher who lived in a clay jar, owned nothing, and was known for his brutal honesty. When Alexander the Great — the most powerful man on earth — heard about Diogenes, he traveled to meet him. He found Diogenes sunbathing outside his jar. Alexander stood over him and said: "I am Alexander the Great. Ask anything of me." Diogenes looked up and said: "Stand a little out of my sun." Alexander\'s generals drew their swords. Alexander laughed and said: "If I were not Alexander, I would wish to be Diogenes." The lesson: the most powerful man in the world envied a homeless philosopher because Diogenes had something Alexander didn\'t — complete freedom from needing anything from anyone. Diogenes had practiced Stoic/Cynic principles to the extreme: he owned nothing, feared nothing, and wanted nothing. The man with nothing was freer than the king of the world.'
      },
      {
        title: 'How to use Stoicism to handle social media envy and comparison anxiety',
        research_context: 'Social media creates a constant stream of other people\'s highlights — and it\'s designed to make you feel inadequate. The Stoics had a name for this: "phantasia" (impressions). Epictetus taught: "It is not the thing itself that disturbs us, but our judgment about the thing." When you see someone\'s vacation photo, promotion announcement, or new car, the photo isn\'t harming you — your judgment that "they have more than me" is causing the harm. Marcus Aurelius advised: "The happiness of your life depends upon the quality of your thoughts." The Stoic antidote: (1) Recognize the impression — "I feel envy." (2) Question the impression — "Is their success really connected to my worth?" (3) Reframe — "I am running my race, they are running theirs." Seneca said: "Comparison is the thief of joy." Modern studies confirm: limiting social media to 30 minutes/day reduces depression and loneliness by 60%.'
      },
      {
        title: 'How to use the Stoic "view from above" to shrink your problems to their proper size',
        research_context: 'Marcus Aurelius\'s most powerful mental exercise was the "view from above" — imagining yourself from high altitude, seeing your life as a tiny speck on a tiny planet in an infinite cosmos. He wrote: "Asia and Europe are mere corners of the universe. The whole ocean is a drop. The whole earth is a point." The exercise: zoom out until your problem is invisible. Your boss yelled at you? Imagine it from space — it\'s nothing. You\'re stressed about a presentation? Visualize the universe — your presentation doesn\'t register. The point isn\'t to minimize real problems, but to kill the anxiety that makes them feel bigger than they are. Neuroscience supports this: the brain\'s amygdala (fear center) calms when you engage the prefrontal cortex (abstract reasoning). By deliberately zooming out, you activate the higher brain that knows the mortgage payment and the online argument are not actually life-threatening emergencies.'
      },
      {
        title: 'Ryan Holiday revived Stoicism for millions — and proved ancient philosophy works in modern business',
        research_context: 'Ryan Holiday was a college dropout who became a marketing director at 21 and a best-selling author by 25. He discovered Stoicism during a difficult period in his career and realized its principles were perfectly suited to modern life. His book "The Obstacle Is the Way" (2014) sold over 2 million copies and was read by NFL coaches, NFL players, UFC fighters, and Fortune 500 CEOs. The book applied Marcus Aurelius\'s insight — "the impediment to action advances action, what stands in the way becomes the way" — to modern challenges. Holiday\'s second Stoic book, "Ego Is the Enemy," argued that ego is the single biggest obstacle to success. His "Daily Stoic" newsletter reaches 3M+ readers. He proved that a 2,000-year-old philosophy — dismissed as academic obscurity — could become a practical tool for millions. His personal practice: "Read the Stoics every morning. Apply one principle. Write about it. Repeat."'
      },
    ]
  ],

  // ─── Urban Survival (canvas_base) ──────────────────────────────────────
  [
    'Urban Survival',
    'canvas_base',
    [
      {
        title: 'Sinking Car Escape: Why you must wait for the water to equalize',
        research_context: 'Approximately 400 people die annually in the US from submerged vehicles. The leading cause of death is panic — victims try to open the door immediately against thousands of pounds of water pressure. The correct protocol: remain calm, undo your seatbelt, open the window (power windows work for 30-60 seconds after submersion), and escape through the window. If the window won\'t open, use the headrest prongs to break the side glass (tempered glass shatters, not the windshield which is laminated). Do NOT try to open the door until the cabin is nearly full of water — only then will the pressure equalize enough to push it open. Children should be released oldest-first so they can help the younger ones. Time window: approximately 60-120 seconds before the car sinks completely.'
      },
      {
        title: 'The Heimlich Maneuver: How abdominal thrusts save 100+ lives every year',
        research_context: 'Choking is the 4th leading cause of unintentional death in the US, killing over 5,000 people annually. The Heimlich maneuver (abdominal thrusts) has a success rate of 86-95% when performed correctly. Technique: stand behind the victim, place your fist above their navel but below the ribcage, grasp with your other hand, and thrust inward and upward in a J-shaped motion. For infants under 1 year: back blows with the heel of your hand between the shoulder blades, then chest thrusts. The universal sign for choking is hands crossed at the throat — if someone can cough or speak, do NOT intervene, as a partial obstruction may clear on its own. The Red Cross officially transitioned from "Heimlich maneuver" to "abdominal thrusts" in its 2021 guidelines to be more descriptive.'
      },
      {
        title: 'Stroke Recognition: The FAST acronym that cuts brain damage by 50%',
        research_context: 'Stroke is the 5th leading cause of death in the US and a leading cause of long-term disability. Every minute a stroke goes untreated, approximately 1.9 million neurons die — that\'s 120 million neurons lost per hour. The FAST acronym saves lives: Face drooping (ask them to smile — is one side numb or drooping?), Arms weakness (ask them to raise both arms — does one drift downward?), Speech difficulty (ask them to repeat a simple sentence — is their speech slurred or strange?), Time to call 911 (note when symptoms first appeared). Thrombolytic (clot-busting) drugs must be administered within 3-4.5 hours of symptom onset. Women often present with atypical symptoms — sudden hiccups, nausea, or chest pain — which means they arrive at hospitals 30 minutes later on average than men, worsening outcomes.'
      },
      {
        title: 'Active Shooter Protocol: The FBI-approved Run-Hide-Fight framework',
        research_context: 'The FBI\'s official active shooter protocol is Run-Hide-Fight, taught to civilians after the 2012 Sandy Hook shooting. Run: Have an escape route in mind before you need one — identify exits the moment you enter any building. Leave your belongings behind. Do not move in a group — spread out to make a harder target. Hide: If escape is impossible, find a room that locks, silence your phone (vibrate mode can be heard), barricade the door with furniture, turn off lights, stay out of the sight line of the door window. Fight: As an absolute last resort, commit fully to disabling the attacker. Improvise weapons (fire extinguisher, chair, pen). The average police response time to an active shooter is 3-10 minutes — the average shooting lasts 5-7 minutes. In 61% of mass shooting events, the incident ended before law enforcement arrived on scene.'
      },
      {
        title: 'Why 90% of Startups Fail: The real survival rate and how to beat it',
        research_context: 'According to data from CB Insights, 90% of startups fail, with 35% failing in year two and 70% by year five. The top three reasons: no market need (42% — building something nobody wants), ran out of cash (29%), and not the right team (23%). The "survival rate" myth: most founders don\'t fail because of a single catastrophe — they fail slowly from ignoring warning signs. Cash runway is the #1 metric: most VCs advise 18-24 months of runway, but the median startup only has 12-16 months. The lean startup methodology (Eric Ries) proved that "build-measure-learn" cycles reduce failure risk by validating demand before burning cash. Startups that pivot once or twice have a 2.5x higher survival rate than those that never pivot. The most dangerous period is months 6-18 — the "valley of death" where initial enthusiasm has faded but revenue hasn\'t materialized. Founders who maintain a side income stream during this period are 40% more likely to survive it.'
      },
      {
        title: 'Hands-Only CPR: How 911 dispatchers walk bystanders through it',
        research_context: 'Cardiac arrest kills over 350,000 people annually in the US outside of hospitals. Bystander CPR doubles or triples survival rates, yet fewer than 46% of cardiac arrest victims receive it before emergency services arrive. Hands-only CPR (compression-only, no rescue breaths) was introduced by the American Heart Association in 2008 specifically to overcome bystander hesitation. Technique: place the heel of one hand on the center of the victim\'s chest (between the nipples), place your other hand on top, lock your elbows, and push hard and fast at 100-120 compressions per minute — the beat of "Stayin\' Alive" by the Bee Gees or "Another One Bites the Dust" by Queen. Push at least 2 inches deep. Continue until paramedics arrive or an AED is available. 911 dispatchers can guide untrained callers through the entire process.'
      },
      {
        title: 'The EpiPen Window: Why anaphylaxis kills in 5–15 minutes',
        research_context: 'Anaphylaxis is a severe, life-threatening allergic reaction that affects 1.6% of the US population (roughly 5 million people). Common triggers include peanuts, tree nuts, shellfish, insect stings, and certain medications. The onset is rapid: within 5-30 minutes of exposure, the throat and tongue swell, blood pressure drops, and airways constrict. Epinephrine (adrenaline) is the ONLY first-line treatment — antihistamines like Benadryl work too slowly to stop anaphylaxis. The EpiPen auto-injector delivers 0.3 mg of epinephrine into the outer thigh (can be injected through clothing). It should be held in place for 3 seconds. The window for effective epinephrine administration is 5-15 minutes after symptoms begin. After injection, the victim MUST still go to the ER — the epinephrine wears off in 15-20 minutes and a second wave of reaction (biphasic anaphylaxis) can hit 1-8 hours later. A second EpiPen should be carried in case symptoms return before EMS arrives.'
      },
      {
        title: 'Home Fire Evacuation: Why modern furniture gives you under 3 minutes',
        research_context: 'In 1975, the average time to escape a house fire was 17 minutes. Today it is under 3 minutes. The reason: synthetic materials in modern furniture (polyester, polyurethane foam) burn faster and produce toxic hydrogen cyanide and carbon monoxide gas that incapacitates before flames ever reach the victim. Smoke inhalation causes 60-80% of fire deaths, not burns. Critical survival rules: install smoke alarms on every level of the home (working smoke alarms cut the risk of dying in a fire by 55%). If you hear an alarm, do not stand up — crawl low under the smoke (breathable air is near the floor). Feel doors with the back of your hand before opening — if hot, use an alternate exit. Have a pre-planned meeting spot outside. Practice a home fire drill twice a year. Most fatal fires occur between 11 PM and 6 AM when families are asleep.'
      },
      {
        title: 'Kitchen Grease Fire: Why water makes it explode and how to smother it',
        research_context: 'Grease fires are the #1 cause of kitchen fires in the US, responsible for over 160,000 home cooking fires annually according to the NFPA. The most dangerous mistake: throwing water on a grease fire. Water sinks beneath the burning oil, instantly vaporizes, expands 1,700 times in volume, and explosively ejects the burning grease across the kitchen — spreading the fire and causing severe burns. Correct protocol: turn off the heat source. Cover the pan with a metal lid (slide it on from the side to avoid the flames). Do NOT use glass lids — they shatter. If a lid isn\'t available, pour baking soda or salt generously over the flames. NEVER use flour (it\'s combustible) or sugar (it caramelizes and burns). A Class K fire extinguisher is the BEST option if available. If the fire has spread beyond the pan, evacuate immediately, close the kitchen door behind you, and call 911 from outside — do not re-enter for any reason. Cooking fires peak on Thanksgiving Day, with 3x the daily average.'
      },
      {
        title: 'After a Car Crash: The 6 things to document for insurance',
        research_context: 'Over 6 million car accidents occur in the US each year. What you do in the first 10 minutes after a crash directly impacts your insurance payout and liability. According to insurance industry guidelines: (1) Check for injuries — do not move injured persons unless there is immediate danger (fire, flooding). (2) Move to safety — if the cars are drivable, pull to the shoulder. If not, stay in the vehicle with your seatbelt on. (3) Call 911 — police reports are considered more credible than either driver\'s account. (4) Document everything — take photos of both vehicles from 4 angles, close-ups of damage, the other car\'s license plate, the intersection/surroundings, skid marks, and road conditions. (5) Exchange information — get the other driver\'s name, phone, insurance company, policy number, and driver\'s license number. Do NOT discuss fault or say "I\'m sorry" — it can be used as an admission of liability. (6) Notify your insurance company — most policies require prompt reporting within 24 hours. The average auto liability claim in 2023 was over $24,000.'
      },
      {
        title: 'Crowd Crush Survival: How to protect your rib cage if trapped standing',
        research_context: 'Crowd crushes (not "panics") are the deadliest crowd disasters. The 2021 Astroworld festival killed 10, the 2010 Love Parade killed 21, and the 1989 Hillsborough disaster killed 97. The primary cause is compressive asphyxia — the force of the crowd compresses the rib cage so the lungs cannot expand, causing oxygen deprivation in under 6 minutes. People do not die from being "trampled" — they die from suffocation while standing upright. Survival techniques: position your arms in front of your chest like a boxer guard — this creates 2-3 inches of breathing space that can save your life. If you fall, curl into a fetal position with your hands laced behind your neck and your knees tucked to your chest to protect your internal organs. Move diagonally through the crowd, not perpendicular, to find gaps. Stay on your feet at all costs — once down in a dense crowd, it is nearly impossible to stand again.'
      },
      {
        title: 'Carbon Monoxide: The silent killer in every home with a furnace',
        research_context: 'Carbon monoxide (CO) is the leading cause of accidental poisoning deaths in the US, killing over 430 people annually and sending 50,000 to emergency rooms — yet most people cannot identify the symptoms. CO is colorless, odorless, and tasteless, produced by incomplete combustion from furnaces, water heaters, gas stoves, generators, and cars running in attached garages. The early symptoms mimic the flu without fever: headache, dizziness, nausea, confusion. At higher concentrations: loss of consciousness, seizures, death. CO exposure at 400 ppm is life-threatening within hours; at 1,200 ppm, death can occur in under 3 minutes. The ONLY way to detect it is a functioning CO detector (required by law in 36 states, installed on every floor and near sleeping areas). If the alarm sounds: evacuate immediately, call 911 from outside, and do NOT re-enter until the fire department clears the building. Never run a generator indoors, in a garage, or within 20 feet of windows — every year, hurricane season causes a spike in CO deaths from improper generator placement.'
      },
      {
        title: 'Fire Extinguisher: The PASS technique most people forget in an emergency',
        research_context: 'Household fire extinguishers can stop 80% of small fires before they spread, yet only 40% of homeowners own one and fewer know how to use it. The NFPA-approved PASS technique is designed to be simple enough to recall under stress. P — Pull the pin (break the tamper seal). A — Aim the nozzle at the base of the fire, NOT the flames (aiming at the flames is the most common mistake). S — Squeeze the handle. S — Sweep the nozzle from side to side. The extinguisher only lasts 8-15 seconds, so aim carefully and start from 6-10 feet away. ABC extinguishers are the standard multipurpose type — they handle ordinary combustibles (wood, paper), flammable liquids (gasoline, grease), and electrical fires. Remember: if the fire is bigger than a small trash can, if the room fills with smoke, or if the extinguisher runs out before the fire is out — evacuate immediately, close the door behind you, and call 911. Fire extinguishers lose pressure over time — check the gauge monthly and replace every 5-12 years depending on the model.'
      },
      {
        title: 'Tourniquet Basics: Why CAT tourniquets are now standard in civilian first aid',
        research_context: 'Severe bleeding is the #1 preventable cause of death in trauma — approximately 60,000 people die annually in the US from hemorrhage. The Combat Application Tourniquet (CAT) was developed for military use in the early 2000s and became standard issue for US soldiers. Studies from the wars in Iraq and Afghanistan showed that early tourniquet application reduced preventable battlefield deaths by 85%. In 2013, the American College of Surgeons launched the Stop the Bleed campaign to train civilians. The CAT gen7 is the current civilian standard. Application rules: place the tourniquet 2-3 inches ABOVE the wound (between the wound and the heart), never over a joint, tighten until bleeding stops (not just slows), and record the time applied. The myth that tourniquets cause limb loss is false — proper use for under 2 hours rarely causes permanent damage. Direct pressure should be attempted first, but if bleeding does not stop within 2-3 minutes, apply the tourniquet immediately.'
      },
      {
        title: 'AED: The defibrillator that talks untrained bystanders through cardiac arrest',
        research_context: 'Automated External Defibrillators (AEDs) increase survival from cardiac arrest by 75% when applied within 3-5 minutes. Yet fewer than 20% of cardiac arrest victims receive an AED shock before EMS arrives. AEDs are designed for untrained users — they literally speak voice prompts: "Call 911", "Remove clothing from the chest", "Attach pads as shown on the pads", "Do not touch the patient — analyzing heart rhythm", "Shock advised — press the flashing button." The AED will NOT shock if no shock is needed — it distinguishes between shockable rhythms (ventricular fibrillation, pulseless ventricular tachycardia) and non-shockable rhythms (asystole, PEA). AEDs are now required in all federal buildings, schools, gyms, and airports. Key rule: you must perform CPR while the AED charges and between shock cycles. Push hard and fast, minimize interruptions. Never use an AED near water or on a metal surface. Check that no one is touching the victim when the shock button is pressed.'
      },
      {
        title: 'Growth Mindset: How the brain rewires itself when you stop fearing failure',
        research_context: 'Stanford psychologist Carol Dweck\'s research on mindset spans 30+ years and shows that people with a "growth mindset" (believing intelligence and ability can be developed) outperform those with a "fixed mindset" (believing traits are innate) by significant margins across academics, sports, and business. The neuroscience: the brain forms new neural pathways throughout life through neuroplasticity — every time you learn from a failure, your prefrontal cortex strengthens connections. Dweck\'s landmark study: students praised for effort ("you worked hard") attempted harder problems and persisted longer than those praised for intelligence ("you\'re so smart"), who avoided challenges to protect their ego. In business, leaders with growth mindset see 47% more engagement and 34% lower turnover. The key reframe: instead of "I failed" → "that approach didn\'t work, so I learned what not to do." Failure isn\'t a verdict — it\'s data. The most resilient entrepreneurs reframe setbacks as tuition for future success.'
      },
      {
        title: 'Hotel Fire Survival: Why you should always know two exits from your room',
        research_context: 'Hotel fires, while rare, have a fatality rate 5 times higher than house fires due to unfamiliarity with the layout. The NDOT (National Disaster and Fire Safety) protocol: upon checking into any hotel room, locate the fire alarm pull station on your floor, count the number of doors between your room and the nearest two exits (you may need to find the exit by feel in zero-visibility smoke), and check that the hallway exit doors are unlocked. If the fire alarm sounds, feel the door with the back of your hand — if hot, do NOT open it. Seal the door gap with wet towels, go to the window (hotel rooms above the 6th floor are too high for fire truck ladders), and signal firefighters. If the door is cool, stay low and crawl to the nearest exit, closing doors behind you. NEVER use the elevator during a fire — the shaft can become a chimney and the doors may open on the fire floor. Never pack your belongings — the MGM Grand 1980 fire killed 85 people, and evidence showed several victims died trying to gather possessions instead of evacuating immediately.'
      },
      {
        title: 'Salary Negotiation: Why the first person to name a number loses leverage',
        research_context: 'Harvard Business School research shows that 60% of professionals never negotiate their first salary offer, leaving an estimated $1 million on the table over a career. The anchoring principle: whoever states the first number sets the psychological range for the entire negotiation — studies show the final settlement consistently lands closer to the first anchor. The BATNA concept (Best Alternative to a Negotiated Agreement) from the Harvard Negotiation Project: your leverage comes from having a viable alternative, not from being aggressive. Women who negotiate are 2.5x more likely to get a raise than those who don\'t, yet only 30% of women negotiate initial offers vs 57% of men. The single most effective tactic: ask "What would it take for us to get to X?" instead of "I want X" — reframing as a collaborative problem vs a demand increases success by 40%. Employers expect you to negotiate — recruiters report that candidates who don\'t negotiate leave 5-10% on the table. The best time to negotiate is after you have an offer but before you accept — that\'s when your leverage peaks.'
      },
      {
        title: 'Heart Attack Signs in Women: Why the crushing chest pain stereotype is dangerous',
        research_context: 'Heart disease is the #1 killer of women in the US, causing 1 in 3 female deaths annually, yet women are 50% more likely than men to have their heart attack misdiagnosed initially. The classic Hollywood symptom — crushing chest pain radiating down the left arm — is how men typically present. Women are more likely to experience: shortness of breath (without chest pain), pain or discomfort in the back, neck, jaw, or stomach, breaking out in a cold sweat, nausea or vomiting, extreme fatigue, lightheadedness. These "atypical" symptoms mean women wait an average of 30 minutes longer than men to seek treatment. The acronym from the American Heart Association: S-S-S (Sudden weakness, Shortness of breath, Sweating/cold sweat). Time is muscle — every 30 minutes of delay increases mortality by 7.5%. Aspirin (325 mg chewed immediately) can reduce mortality by 23% if taken during a suspected heart attack. If you suspect a heart attack in yourself or someone else, call 911 immediately — driving yourself to the hospital increases the risk of a crash if you lose consciousness.'
      },
      {
        title: 'Meditation: How 10 minutes of daily mindfulness rewires your brain for focus and calm',
        research_context: 'Harvard neuroscientist Sara Lazar\'s 2011 study showed that 8 weeks of daily mindfulness meditation (30 minutes/day) physically increased gray matter density in the hippocampus (learning and memory) and decreased it in the amygdala (stress, fear, anxiety). Even 10 minutes per day has measurable effects: a 2017 study found that 10-minute meditation sessions reduced cortisol (the primary stress hormone) by 20%. The default mode network (DMN) — the brain region responsible for mind-wandering and rumination — calms significantly after consistent meditation practice, which correlates with reduced anxiety and depression. Corporate adoption: Google\'s "Search Inside Yourself" program has been completed by thousands of employees, reporting a 30% reduction in stress and 25% improvement in focus. The simplest technique: box breathing (4-4-4-4: inhale 4 seconds, hold 4, exhale 4, hold 4) activates the parasympathetic nervous system and can lower heart rate in under 2 minutes. The most common obstacle: people quit because they think they\'re "bad at meditating" — but the entire point is noticing your mind wandering and gently bringing it back. That IS the exercise, not a failure.'
      },
    ]
  ],
];
